### ISSUE TITLE
Teacher model training process inquiry

### ISSUE THREAD

**Issue by Yang-ChiaHsiang** [haseebaslam95/MT-PKDOT#1]
Hello, I have studied the paper "Multi Teacher Privileged Knowledge Distillation for Multimodal Expression Recognition" and am very interested in your creation. I would like to confirm with you about the "training process of the teacher model", especially T-Net ( TransformNet).

Is the teacher model trained in two stages? In the first stage, the teacher model is trained. Is T-Net trained after training?

**Comment by haseebaslam95** [comment]
Hello. Thanks for your interest in our work.

Since T-Net is trained on the features of the multiple backbones, both strategies would work. However, since in this work we work with pretrained teachers, we separately trained the T-Net on the features.
